/*
 * Translator Knowledge Beacon API
 * This is the Translator Knowledge Beacon Aggregator web service application programming interface (API). 
 *
 * OpenAPI spec version: 1.0.12
 * Contact: richard@starinformatics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package bio.knowledge.client.api;

import java.util.ArrayList;
import java.util.List;

import org.junit.Ignore;
import org.junit.Test;

import bio.knowledge.client.ApiException;
import bio.knowledge.client.model.Summary;

/**
 * API tests for SummaryApi
 */
@Ignore
public class SummaryApiTest {

    private final SummaryApi api = new SummaryApi();

    
    /**
     * 
     *
     * Get a list of types and # of instances in the knowledge source, and a link to the API call for the list of equivalent terminology 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void linkedTypesTest() throws ApiException {
    	List<String> beacons = new ArrayList<String>() ;
        String sessionId = "";
        List<Summary> response = api.linkedTypes(beacons, sessionId);
    }
    
}
