/*
 * Translator Knowledge.Bio API
 * Documentation of the Translator Knowledge.Bio (TKBio) knowledge sources query web service application programming interfaces. Learn more about [TKBio](https://github.com/STARInformatics/tkbio) 
 *
 * OpenAPI spec version: 4.0.1
 * Contact: richard@starinformatics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Identifiers;
import io.swagger.client.model.InlineResponse2001;
import io.swagger.client.model.InlineResponse2002;
import io.swagger.client.model.InlineResponse201;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for XrefsApi
 */
@Ignore
public class XrefsApiTest {

    private final XrefsApi api = new XrefsApi();

    
    /**
     * 
     *
     * Retrieves a list of cross-referencing identifiers associated with an specifically identified concept, typically, a concept selected from the list of concepts originally returned by a /concepts API call. This API call will typically be run against the same KS (only) from which the originally selected concept was retrieved. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getConceptXRefsTest() throws ApiException {
        String conceptId = null;
        List<InlineResponse2001> response = api.getConceptXRefs(conceptId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Retrieves the list of concepts with that match one or more cross-references posted in the previously initiated query session. This new list of concepts is returned with the full list of their associated cross-references. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getXRefConceptsTest() throws ApiException {
        String queryId = null;
        List<InlineResponse2002> response = api.getXRefConcepts(queryId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Posts a list of cross-reference identifiers to a given KS endpoint, initiating a query session 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postXRefQueryTest() throws ApiException {
        List<Identifiers> identifiers = null;
        InlineResponse201 response = api.postXRefQuery(identifiers);

        // TODO: test validations
    }
    
}
