package bio.knowledge.web.design;

import org.vaadin.tokenfield.TokenField;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.Slider;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Upload;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.VerticalSplitPanel;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DesktopDesign extends VerticalLayout {
	protected VerticalSplitPanel desktopSplitPanel;
	protected HorizontalLayout viewingConcepts;
	protected TextField search;
	protected Button searchBtn;
	protected HorizontalLayout popUpLayout;
	protected TabSheet dataTabSheet;
	protected VerticalLayout relationsTab;
	protected VerticalLayout evidenceTab;
	protected VerticalLayout referenceTab;
	protected VerticalLayout referenceLayout;
	protected HorizontalLayout cmbar;
	protected Upload loadMap;
	protected Button saveBtn;
	protected Button clearMapBtn;
	protected Button searchMapLibraryBtn;
	protected Button centerMapBtn;
	protected NativeSelect cmLayoutSelect;
	protected NativeSelect colorSelect;
	protected HorizontalLayout cmPanel;
	protected Button showLegendBtn;
	protected Slider zoomSlider;
	protected Label conceptMapNameLabel;

	public DesktopDesign() {
		Design.read(this);
	}
}
