/*
 * Translator Knowledge Beacon API
 * This is the Translator Knowledge Beacon web service application programming interface (API).  This OpenAPI (\"Swagger\") document may be used as the input specification into a tool like [Swagger-Codegen](https://github.com/swagger-api/swagger-codegen/blob/master/README.md) to generate client and server code stubs implementing the API, in any one of several supported computer languages and frameworks. In order to customize usage to your web site, you should change the 'host' directive below to your hostname.  Note that where the term 'local' is used below to describe an identifier or other resource, it is referring to the specific Knowledge Source (KS) upon which the Knowledge Beacon API is hosted. 
 *
 * OpenAPI spec version: 4.0.6
 * Contact: richard@starinformatics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package bio.knowledge.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ExactMatchesExactMatches
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-27T09:44:03.540-07:00")
public class ExactMatchesExactMatches {
  @SerializedName("id")
  private String id = null;

  @SerializedName("evidenceCode")
  private String evidenceCode = null;

  @SerializedName("reference")
  private String reference = null;

  public ExactMatchesExactMatches id(String id) {
    this.id = id;
    return this;
  }

   /**
   * [CURIE](https://www.w3.org/TR/curie/) identifier of asserted exact matching concept 
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "[CURIE](https://www.w3.org/TR/curie/) identifier of asserted exact matching concept ")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ExactMatchesExactMatches evidenceCode(String evidenceCode) {
    this.evidenceCode = evidenceCode;
    return this;
  }

   /**
   * identifier of [GENE Ontology Evidence Codes](http://geneontology.org/page/guide-go-evidence-codes) 
   * @return evidenceCode
  **/
  @ApiModelProperty(example = "null", value = "identifier of [GENE Ontology Evidence Codes](http://geneontology.org/page/guide-go-evidence-codes) ")
  public String getEvidenceCode() {
    return evidenceCode;
  }

  public void setEvidenceCode(String evidenceCode) {
    this.evidenceCode = evidenceCode;
  }

  public ExactMatchesExactMatches reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * [CURIE](https://www.w3.org/TR/curie/) identifier of supporting reference 
   * @return reference
  **/
  @ApiModelProperty(example = "null", value = "[CURIE](https://www.w3.org/TR/curie/) identifier of supporting reference ")
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExactMatchesExactMatches exactMatchesExactMatches = (ExactMatchesExactMatches) o;
    return Objects.equals(this.id, exactMatchesExactMatches.id) &&
        Objects.equals(this.evidenceCode, exactMatchesExactMatches.evidenceCode) &&
        Objects.equals(this.reference, exactMatchesExactMatches.reference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, evidenceCode, reference);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExactMatchesExactMatches {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    evidenceCode: ").append(toIndentedString(evidenceCode)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

