/*
 * Translator Knowledge Beacon Aggregator API
 * This is the Translator Knowledge Beacon Aggregator web service application programming interface (API) that provides integrated access to a pool of knowledge sources publishing concepts and relations through the Translator Knowledge Beacon API. This API is similar to that of the latter mentioned API with the addition of some extra informative endpoints plus session identifier and beacon indices. These latter identifiers are locally assigned numeric indices provided to track the use of specific registered beacons within the aggregator API itself. 
 *
<<<<<<< HEAD:api/client/src/main/java/bio/knowledge/client/model/BeaconPredicateBeacon.java
 * OpenAPI spec version: 1.0.7
=======
 * OpenAPI spec version: 1.0.10
>>>>>>> b6eef7329db817d4f4fb123167501cff4ffdf751:api/client/src/main/java/bio/knowledge/client/model/ServerKnowledgeMapObject.java
 * Contact: richard@starinformatics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package bio.knowledge.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * ServerKnowledgeMapObject
 */
<<<<<<< HEAD:api/client/src/main/java/bio/knowledge/client/model/BeaconPredicateBeacon.java
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-20T20:09:45.790-08:00")
public class BeaconPredicateBeacon {
  @SerializedName("beacon")
  private String beacon = null;

=======
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-23T15:54:45.861-07:00")
public class ServerKnowledgeMapObject {
>>>>>>> b6eef7329db817d4f4fb123167501cff4ffdf751:api/client/src/main/java/bio/knowledge/client/model/ServerKnowledgeMapObject.java
  @SerializedName("id")
  private String id = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("prefixes")
  private List<String> prefixes = new ArrayList<String>();

  public ServerKnowledgeMapObject id(String id) {
    this.id = id;
    return this;
  }

   /**
   * the CURIE designating the concept type of a  statement object 
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "the CURIE designating the concept type of a  statement object ")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ServerKnowledgeMapObject label(String label) {
    this.label = label;
    return this;
  }

   /**
   * the human readable label of the concept type of a statement object 
   * @return label
  **/
  @ApiModelProperty(example = "null", value = "the human readable label of the concept type of a statement object ")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public ServerKnowledgeMapObject prefixes(List<String> prefixes) {
    this.prefixes = prefixes;
    return this;
  }

  public ServerKnowledgeMapObject addPrefixesItem(String prefixesItem) {
    this.prefixes.add(prefixesItem);
    return this;
  }

   /**
   * Get prefixes
   * @return prefixes
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getPrefixes() {
    return prefixes;
  }

  public void setPrefixes(List<String> prefixes) {
    this.prefixes = prefixes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServerKnowledgeMapObject serverKnowledgeMapObject = (ServerKnowledgeMapObject) o;
    return Objects.equals(this.id, serverKnowledgeMapObject.id) &&
        Objects.equals(this.label, serverKnowledgeMapObject.label) &&
        Objects.equals(this.prefixes, serverKnowledgeMapObject.prefixes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, label, prefixes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServerKnowledgeMapObject {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    prefixes: ").append(toIndentedString(prefixes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

