/*
 * Translator Knowledge Beacon Aggregator API
 * This is the Translator Knowledge Beacon Aggregator web service application programming interface (API) that provides integrated access to a pool of knowledge sources publishing concepts and relations through the Translator Knowledge Beacon API. This API is similar to that of the latter mentioned API with the addition of some extra informative endpoints plus session identifier and beacon indices. These latter identifiers are locally assigned numeric indices provided to track the use of specific registered beacons within the aggregator API itself. 
 *
<<<<<<< HEAD:api/client/src/main/java/bio/knowledge/client/model/BeaconStatement.java
 * OpenAPI spec version: 1.0.7
=======
 * OpenAPI spec version: 1.0.10
>>>>>>> b6eef7329db817d4f4fb123167501cff4ffdf751:api/client/src/main/java/bio/knowledge/client/model/ServerStatement.java
 * Contact: richard@starinformatics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package bio.knowledge.client.model;

import java.util.Objects;
<<<<<<< HEAD:api/client/src/main/java/bio/knowledge/client/model/BeaconStatement.java
import bio.knowledge.client.model.BeaconStatementObject;
import bio.knowledge.client.model.BeaconStatementPredicate;
import bio.knowledge.client.model.BeaconStatementSubject;
=======
import bio.knowledge.client.model.ServerStatementObject;
import bio.knowledge.client.model.ServerStatementPredicate;
import bio.knowledge.client.model.ServerStatementSubject;
>>>>>>> b6eef7329db817d4f4fb123167501cff4ffdf751:api/client/src/main/java/bio/knowledge/client/model/ServerStatement.java
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ServerStatement
 */
<<<<<<< HEAD:api/client/src/main/java/bio/knowledge/client/model/BeaconStatement.java
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-20T20:18:11.941-08:00")
public class BeaconStatement {
=======
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-23T15:54:45.861-07:00")
public class ServerStatement {
>>>>>>> b6eef7329db817d4f4fb123167501cff4ffdf751:api/client/src/main/java/bio/knowledge/client/model/ServerStatement.java
  @SerializedName("id")
  private String id = null;

  @SerializedName("subject")
  private ServerStatementSubject subject = null;

  @SerializedName("predicate")
  private ServerStatementPredicate predicate = null;

  @SerializedName("object")
  private ServerStatementObject object = null;

  @SerializedName("beacon")
  private Integer beacon = null;

  public ServerStatement id(String id) {
    this.id = id;
    return this;
  }

   /**
   * CURIE-encoded identifier for statement (can be used to retrieve associated evidence)
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "CURIE-encoded identifier for statement (can be used to retrieve associated evidence)")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ServerStatement subject(ServerStatementSubject subject) {
    this.subject = subject;
    return this;
  }

   /**
   * Get subject
   * @return subject
  **/
  @ApiModelProperty(example = "null", value = "")
  public ServerStatementSubject getSubject() {
    return subject;
  }

  public void setSubject(ServerStatementSubject subject) {
    this.subject = subject;
  }

  public ServerStatement predicate(ServerStatementPredicate predicate) {
    this.predicate = predicate;
    return this;
  }

   /**
   * Get predicate
   * @return predicate
  **/
  @ApiModelProperty(example = "null", value = "")
  public ServerStatementPredicate getPredicate() {
    return predicate;
  }

  public void setPredicate(ServerStatementPredicate predicate) {
    this.predicate = predicate;
  }

  public ServerStatement object(ServerStatementObject object) {
    this.object = object;
    return this;
  }

   /**
   * Get object
   * @return object
  **/
  @ApiModelProperty(example = "null", value = "")
  public ServerStatementObject getObject() {
    return object;
  }

  public void setObject(ServerStatementObject object) {
    this.object = object;
  }

  public ServerStatement beacon(Integer beacon) {
    this.beacon = beacon;
    return this;
  }

   /**
   * aggregator assigned beacon index number 
   * @return beacon
  **/
  @ApiModelProperty(example = "null", value = "aggregator assigned beacon index number ")
  public Integer getBeacon() {
    return beacon;
  }

  public void setBeacon(Integer beacon) {
    this.beacon = beacon;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServerStatement serverStatement = (ServerStatement) o;
    return Objects.equals(this.id, serverStatement.id) &&
        Objects.equals(this.subject, serverStatement.subject) &&
        Objects.equals(this.predicate, serverStatement.predicate) &&
        Objects.equals(this.object, serverStatement.object) &&
        Objects.equals(this.beacon, serverStatement.beacon);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, subject, predicate, object, beacon);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServerStatement {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    predicate: ").append(toIndentedString(predicate)).append("\n");
    sb.append("    object: ").append(toIndentedString(object)).append("\n");
    sb.append("    beacon: ").append(toIndentedString(beacon)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

